on: pull_request
name: giphy status check self run
jobs:
  giphy:
    name: giphy status check self run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: PR Status Giphy
      uses: ./
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
